name: aina_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^3.0.10
  firebase_core: ^2.4.1
  injectable: ^2.1.0
  auto_route: ^5.0.4
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.4.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  rxdart: ^0.27.7
  pinput: ^2.2.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  auto_route_generator: ^5.0.2
  injectable_generator:
  json_serializable: ^6.5.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400